export const products = [
  {
    id: 204548398,
    name: "Farah Colbert seersucker stripe shorts in true navy",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548437,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613668,
    productType: "Product",
    url: "farah/farah-colbert-seersucker-stripe-shorts-in-true-navy/prd/204548398?clr=navy&colourWayId=204548437",
    imageUrl:
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-true-navy/204548398-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-true-navy/204548398-2",
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-true-navy/204548398-3",
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-true-navy/204548398-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548362,
    name: "Farah Elm stretch slim fit jeans in dark blue",
    price: {
      current: {
        value: 129,
        text: "$129.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Blue",
    colourWayId: 204548363,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613620,
    productType: "Product",
    url: "farah/farah-elm-stretch-slim-fit-jeans-in-dark-blue/prd/204548362?clr=blue&colourWayId=204548363",
    imageUrl:
      "images.asos-media.com/products/farah-elm-stretch-slim-fit-jeans-in-dark-blue/204548362-1-blue",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-elm-stretch-slim-fit-jeans-in-dark-blue/204548362-2",
      "images.asos-media.com/products/farah-elm-stretch-slim-fit-jeans-in-dark-blue/204548362-3",
      "images.asos-media.com/products/farah-elm-stretch-slim-fit-jeans-in-dark-blue/204548362-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548192,
    name: "Farah Colbert plain swim shorts in true navy",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548194,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613638,
    productType: "Product",
    url: "farah/farah-colbert-plain-swim-shorts-in-true-navy/prd/204548192?clr=navy&colourWayId=204548194",
    imageUrl:
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-true-navy/204548192-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-true-navy/204548192-2",
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-true-navy/204548192-3",
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-true-navy/204548192-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548490,
    name: "Farah Steen long sleeve shirt in peach",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Orange",
    colourWayId: 204548495,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613608,
    productType: "Product",
    url: "farah/farah-steen-long-sleeve-shirt-in-peach/prd/204548490?clr=orange&colourWayId=204548495",
    imageUrl:
      "images.asos-media.com/products/farah-steen-long-sleeve-shirt-in-peach/204548490-1-orange",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-steen-long-sleeve-shirt-in-peach/204548490-2",
      "images.asos-media.com/products/farah-steen-long-sleeve-shirt-in-peach/204548490-3",
      "images.asos-media.com/products/farah-steen-long-sleeve-shirt-in-peach/204548490-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548590,
    name: "Farah Osborne canvas regular fit pants in true navy",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548592,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613598,
    productType: "Product",
    url: "farah/farah-osborne-canvas-regular-fit-pants-in-true-navy/prd/204548590?clr=navy&colourWayId=204548592",
    imageUrl:
      "images.asos-media.com/products/farah-osborne-canvas-regular-fit-pants-in-true-navy/204548590-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-osborne-canvas-regular-fit-pants-in-true-navy/204548590-2",
      "images.asos-media.com/products/farah-osborne-canvas-regular-fit-pants-in-true-navy/204548590-3",
      "images.asos-media.com/products/farah-osborne-canvas-regular-fit-pants-in-true-navy/204548590-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203502456,
    name: "Farah Brewer slim fit cotton oxford shirt in green",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Green",
    colourWayId: 203502467,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121188694,
    productType: "Product",
    url: "farah/farah-brewer-slim-fit-cotton-oxford-shirt-in-green/prd/203502456?clr=green&colourWayId=203502467",
    imageUrl:
      "images.asos-media.com/products/farah-brewer-slim-fit-cotton-oxford-shirt-in-green/203502456-1-green",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-brewer-slim-fit-cotton-oxford-shirt-in-green/203502456-2",
      "images.asos-media.com/products/farah-brewer-slim-fit-cotton-oxford-shirt-in-green/203502456-3",
      "images.asos-media.com/products/farah-brewer-slim-fit-cotton-oxford-shirt-in-green/203502456-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548054,
    name: "Farah Ronnie oversized terry t-shirt in true navy",
    price: {
      current: {
        value: 77,
        text: "$77.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548071,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613601,
    productType: "Product",
    url: "farah/farah-ronnie-oversized-terry-t-shirt-in-true-navy/prd/204548054?clr=navy&colourWayId=204548071",
    imageUrl:
      "images.asos-media.com/products/farah-ronnie-oversized-terry-t-shirt-in-true-navy/204548054-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-ronnie-oversized-terry-t-shirt-in-true-navy/204548054-2",
      "images.asos-media.com/products/farah-ronnie-oversized-terry-t-shirt-in-true-navy/204548054-3",
      "images.asos-media.com/products/farah-ronnie-oversized-terry-t-shirt-in-true-navy/204548054-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548055,
    name: "Farah Meadows T-shirt in true navy with striped collar",
    price: {
      current: {
        value: 77,
        text: "$77.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548057,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613609,
    productType: "Product",
    url: "farah/farah-meadows-t-shirt-in-true-navy-with-striped-collar/prd/204548055?clr=navy&colourWayId=204548057",
    imageUrl:
      "images.asos-media.com/products/farah-meadows-t-shirt-in-true-navy-with-striped-collar/204548055-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-meadows-t-shirt-in-true-navy-with-striped-collar/204548055-2",
      "images.asos-media.com/products/farah-meadows-t-shirt-in-true-navy-with-striped-collar/204548055-3",
      "images.asos-media.com/products/farah-meadows-t-shirt-in-true-navy-with-striped-collar/204548055-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548079,
    name: "Farah Danny t-shirt in dark gray heather",
    price: {
      current: {
        value: 52,
        text: "$52.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Gray",
    colourWayId: 204548109,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613663,
    productType: "Product",
    url: "farah/farah-danny-t-shirt-in-dark-gray-heather/prd/204548079?clr=gray&colourWayId=204548109",
    imageUrl:
      "images.asos-media.com/products/farah-danny-t-shirt-in-dark-gray-heather/204548079-1-grey",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-danny-t-shirt-in-dark-gray-heather/204548079-2",
      "images.asos-media.com/products/farah-danny-t-shirt-in-dark-gray-heather/204548079-3",
      "images.asos-media.com/products/farah-danny-t-shirt-in-dark-gray-heather/204548079-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548117,
    name: "Farah Daytona cotton stripe t-shirt in true navy",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548135,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613654,
    productType: "Product",
    url: "farah/farah-daytona-cotton-stripe-t-shirt-in-true-navy/prd/204548117?clr=navy&colourWayId=204548135",
    imageUrl:
      "images.asos-media.com/products/farah-daytona-cotton-stripe-t-shirt-in-true-navy/204548117-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-daytona-cotton-stripe-t-shirt-in-true-navy/204548117-2",
      "images.asos-media.com/products/farah-daytona-cotton-stripe-t-shirt-in-true-navy/204548117-3",
      "images.asos-media.com/products/farah-daytona-cotton-stripe-t-shirt-in-true-navy/204548117-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548241,
    name: "Farah Tunel t-shirt in light heather gray marl with vintage plaid graphics",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Gray",
    colourWayId: 204548248,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613611,
    productType: "Product",
    url: "farah/farah-tunel-t-shirt-in-light-heather-gray-marl-with-vintage-plaid-graphics/prd/204548241?clr=gray&colourWayId=204548248",
    imageUrl:
      "images.asos-media.com/products/farah-tunel-t-shirt-in-light-heather-gray-marl-with-vintage-plaid-graphics/204548241-1-grey",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-tunel-t-shirt-in-light-heather-gray-marl-with-vintage-plaid-graphics/204548241-2",
      "images.asos-media.com/products/farah-tunel-t-shirt-in-light-heather-gray-marl-with-vintage-plaid-graphics/204548241-3",
      "images.asos-media.com/products/farah-tunel-t-shirt-in-light-heather-gray-marl-with-vintage-plaid-graphics/204548241-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548282,
    name: "Farah Danny T-shirt in orange mandarin",
    price: {
      current: {
        value: 52,
        text: "$52.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Orange",
    colourWayId: 204548283,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613613,
    productType: "Product",
    url: "farah/farah-danny-t-shirt-in-orange-mandarin/prd/204548282?clr=orange&colourWayId=204548283",
    imageUrl:
      "images.asos-media.com/products/farah-danny-t-shirt-in-orange-mandarin/204548282-1-orange",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-danny-t-shirt-in-orange-mandarin/204548282-2",
      "images.asos-media.com/products/farah-danny-t-shirt-in-orange-mandarin/204548282-3",
      "images.asos-media.com/products/farah-danny-t-shirt-in-orange-mandarin/204548282-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548337,
    name: "Farah Danny T-shirt in teal green",
    price: {
      current: {
        value: 52,
        text: "$52.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Green",
    colourWayId: 204548338,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613628,
    productType: "Product",
    url: "farah/farah-danny-t-shirt-in-teal-green/prd/204548337?clr=green&colourWayId=204548338",
    imageUrl:
      "images.asos-media.com/products/farah-danny-t-shirt-in-teal-green/204548337-1-green",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-danny-t-shirt-in-teal-green/204548337-2",
      "images.asos-media.com/products/farah-danny-t-shirt-in-teal-green/204548337-3",
      "images.asos-media.com/products/farah-danny-t-shirt-in-teal-green/204548337-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548438,
    name: "Farah Stacy pocket t-shirt in true navy",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548454,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613617,
    productType: "Product",
    url: "farah/farah-stacy-pocket-t-shirt-in-true-navy/prd/204548438?clr=navy&colourWayId=204548454",
    imageUrl:
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-true-navy/204548438-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-true-navy/204548438-2",
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-true-navy/204548438-3",
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-true-navy/204548438-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548458,
    name: "Farah Stacy pocket T-shirt in white",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "White",
    colourWayId: 204548494,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613665,
    productType: "Product",
    url: "farah/farah-stacy-pocket-t-shirt-in-white/prd/204548458?clr=white&colourWayId=204548494",
    imageUrl:
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-white/204548458-1-white",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-white/204548458-2",
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-white/204548458-3",
      "images.asos-media.com/products/farah-stacy-pocket-t-shirt-in-white/204548458-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548634,
    name: "Farah Venice t-shirt in white with back print",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "White",
    colourWayId: 204548642,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613657,
    productType: "Product",
    url: "farah/farah-venice-t-shirt-in-white-with-back-print/prd/204548634?clr=white&colourWayId=204548642",
    imageUrl:
      "images.asos-media.com/products/farah-venice-t-shirt-in-white-with-back-print/204548634-1-white",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-venice-t-shirt-in-white-with-back-print/204548634-2",
      "images.asos-media.com/products/farah-venice-t-shirt-in-white-with-back-print/204548634-3",
      "images.asos-media.com/products/farah-venice-t-shirt-in-white-with-back-print/204548634-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548662,
    name: "Farah Jeff t-shirt in white with back print",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "White",
    colourWayId: 204548670,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613604,
    productType: "Product",
    url: "farah/farah-jeff-t-shirt-in-white-with-back-print/prd/204548662?clr=white&colourWayId=204548670",
    imageUrl:
      "images.asos-media.com/products/farah-jeff-t-shirt-in-white-with-back-print/204548662-1-white",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-jeff-t-shirt-in-white-with-back-print/204548662-2",
      "images.asos-media.com/products/farah-jeff-t-shirt-in-white-with-back-print/204548662-3",
      "images.asos-media.com/products/farah-jeff-t-shirt-in-white-with-back-print/204548662-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548150,
    name: "Farah Murphy tapped logo swim shorts in navy",
    price: {
      current: {
        value: 77,
        text: "$77.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548159,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613636,
    productType: "Product",
    url: "farah/farah-murphy-tapped-logo-swim-shorts-in-navy/prd/204548150?clr=navy&colourWayId=204548159",
    imageUrl:
      "images.asos-media.com/products/farah-murphy-tapped-logo-swim-shorts-in-navy/204548150-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-murphy-tapped-logo-swim-shorts-in-navy/204548150-2",
      "images.asos-media.com/products/farah-murphy-tapped-logo-swim-shorts-in-navy/204548150-3",
      "images.asos-media.com/products/farah-murphy-tapped-logo-swim-shorts-in-navy/204548150-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548184,
    name: "Farah Murphy swim shorts in navy floral",
    price: {
      current: {
        value: 77,
        text: "$77.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 204548193,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613656,
    productType: "Product",
    url: "farah/farah-murphy-swim-shorts-in-navy-floral/prd/204548184?clr=navy&colourWayId=204548193",
    imageUrl:
      "images.asos-media.com/products/farah-murphy-swim-shorts-in-navy-floral/204548184-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-murphy-swim-shorts-in-navy-floral/204548184-2",
      "images.asos-media.com/products/farah-murphy-swim-shorts-in-navy-floral/204548184-3",
      "images.asos-media.com/products/farah-murphy-swim-shorts-in-navy-floral/204548184-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548230,
    name: "Farah Colbert seersucker stripe shorts in red",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Pink",
    colourWayId: 204548242,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613660,
    productType: "Product",
    url: "farah/farah-colbert-seersucker-stripe-shorts-in-red/prd/204548230?clr=pink&colourWayId=204548242",
    imageUrl:
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-red/204548230-1-pink",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-red/204548230-2",
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-red/204548230-3",
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-red/204548230-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548516,
    name: "Farah Colbert seersucker stripe shorts in yellow - Exclusive to ASOS",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Yellow",
    colourWayId: 204548524,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613661,
    productType: "Product",
    url: "farah/farah-colbert-seersucker-stripe-shorts-in-yellow-exclusive-to-asos/prd/204548516?clr=yellow&colourWayId=204548524",
    imageUrl:
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-yellow-exclusive-to-asos/204548516-1-yellow",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-yellow-exclusive-to-asos/204548516-2",
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-yellow-exclusive-to-asos/204548516-3",
      "images.asos-media.com/products/farah-colbert-seersucker-stripe-shorts-in-yellow-exclusive-to-asos/204548516-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204548609,
    name: "Farah Colbert plain swim shorts in indigo green",
    price: {
      current: {
        value: 69,
        text: "$69.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Blue",
    colourWayId: 204548613,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 127613662,
    productType: "Product",
    url: "farah/farah-colbert-plain-swim-shorts-in-indigo-green/prd/204548609?clr=blue&colourWayId=204548613",
    imageUrl:
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-indigo-green/204548609-1-blue",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-indigo-green/204548609-2",
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-indigo-green/204548609-3",
      "images.asos-media.com/products/farah-colbert-plain-swim-shorts-in-indigo-green/204548609-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203511267,
    name: "Farah Ward long sleeve cotton rugby shirt in navy",
    price: {
      current: {
        value: 129,
        text: "$129.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 203511268,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121211051,
    productType: "Product",
    url: "farah/farah-ward-long-sleeve-cotton-rugby-shirt-in-navy/prd/203511267?clr=navy&colourWayId=203511268",
    imageUrl:
      "images.asos-media.com/products/farah-ward-long-sleeve-cotton-rugby-shirt-in-navy/203511267-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-ward-long-sleeve-cotton-rugby-shirt-in-navy/203511267-2",
      "images.asos-media.com/products/farah-ward-long-sleeve-cotton-rugby-shirt-in-navy/203511267-3",
      "images.asos-media.com/products/farah-ward-long-sleeve-cotton-rugby-shirt-in-navy/203511267-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203502436,
    name: "Farah Haslam cotton polo in navy",
    price: {
      current: {
        value: 95,
        text: "$95.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 203502442,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121188691,
    productType: "Product",
    url: "farah/farah-haslam-cotton-polo-in-navy/prd/203502436?clr=navy&colourWayId=203502442",
    imageUrl:
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-navy/203502436-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-navy/203502436-2",
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-navy/203502436-3",
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-navy/203502436-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 204110935,
    name: "Farah Reggie t-shirt in gray heather with front and back graphics Exclusive to ASOS",
    price: {
      current: {
        value: 45,
        text: "$45.00",
      },
      previous: {
        value: 60,
        text: "$60.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Gray",
    colourWayId: 204110955,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 125059094,
    productType: "Product",
    url: "farah/farah-reggie-t-shirt-in-gray-heather-with-front-and-back-graphics-exclusive-to-asos/prd/204110935?clr=gray&colourWayId=204110955",
    imageUrl:
      "images.asos-media.com/products/farah-reggie-t-shirt-in-gray-heather-with-front-and-back-graphics-exclusive-to-asos/204110935-1-grey",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-reggie-t-shirt-in-gray-heather-with-front-and-back-graphics-exclusive-to-asos/204110935-2",
      "images.asos-media.com/products/farah-reggie-t-shirt-in-gray-heather-with-front-and-back-graphics-exclusive-to-asos/204110935-3",
      "images.asos-media.com/products/farah-reggie-t-shirt-in-gray-heather-with-front-and-back-graphics-exclusive-to-asos/204110935-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 201759634,
    name: "Farah hawaiian print swim trunks in orange",
    price: {
      current: {
        value: 31.5,
        text: "$31.50",
      },
      previous: {
        value: 42,
        text: "$42.00",
      },
      rrp: {
        value: 58,
        text: "$58.00",
      },
      isMarkedDown: true,
      isOutletPrice: true,
      currency: "USD",
    },
    colour: "Orange",
    colourWayId: 201759637,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 114878706,
    productType: "Product",
    url: "farah/farah-hawaiian-print-swim-trunks-in-orange/prd/201759634?clr=orange&colourWayId=201759637",
    imageUrl:
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-orange/201759634-1-orange",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-orange/201759634-2",
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-orange/201759634-3",
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-orange/201759634-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203502351,
    name: "Farah Tim crew neck cotton sweatshirt in navy",
    price: {
      current: {
        value: 95,
        text: "$95.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 203502367,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121188701,
    productType: "Product",
    url: "farah/farah-tim-crew-neck-cotton-sweatshirt-in-navy/prd/203502351?clr=navy&colourWayId=203502367",
    imageUrl:
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-navy/203502351-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-navy/203502351-2",
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-navy/203502351-3",
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-navy/203502351-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202970027,
    name: "Farah Sepel patch twill shorts in navy",
    price: {
      current: {
        value: 71.5,
        text: "$71.50",
      },
      previous: {
        value: 95,
        text: "$95.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "NAVY",
    colourWayId: 202970054,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228374,
    productType: "Product",
    url: "farah/farah-sepel-patch-twill-shorts-in-navy/prd/202970027?clr=navy&colourWayId=202970054",
    imageUrl:
      "images.asos-media.com/products/farah-sepel-patch-twill-shorts-in-navy/202970027-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-sepel-patch-twill-shorts-in-navy/202970027-2",
      "images.asos-media.com/products/farah-sepel-patch-twill-shorts-in-navy/202970027-3",
      "images.asos-media.com/products/farah-sepel-patch-twill-shorts-in-navy/202970027-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 201770924,
    name: "Farah sweat in white",
    price: {
      current: {
        value: 60,
        text: "$60.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: 99,
        text: "$99.00",
      },
      isMarkedDown: false,
      isOutletPrice: true,
      currency: "USD",
    },
    colour: "WHITE",
    colourWayId: 201770937,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 114898895,
    productType: "Product",
    url: "farah/farah-sweat-in-white/prd/201770924?clr=white&colourWayId=201770937",
    imageUrl:
      "images.asos-media.com/products/farah-sweat-in-white/201770924-1-white",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-sweat-in-white/201770924-2",
      "images.asos-media.com/products/farah-sweat-in-white/201770924-3",
      "images.asos-media.com/products/farah-sweat-in-white/201770924-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969967,
    name: "Farah Danny cotton t-shirt in blue",
    price: {
      current: {
        value: 43,
        text: "$43.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "BLUE",
    colourWayId: 202969987,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228402,
    productType: "Product",
    url: "farah/farah-danny-cotton-t-shirt-in-blue/prd/202969967?clr=blue&colourWayId=202969987",
    imageUrl:
      "images.asos-media.com/products/farah-danny-cotton-t-shirt-in-blue/202969967-1-blue",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-danny-cotton-t-shirt-in-blue/202969967-2",
      "images.asos-media.com/products/farah-danny-cotton-t-shirt-in-blue/202969967-3",
      "images.asos-media.com/products/farah-danny-cotton-t-shirt-in-blue/202969967-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203502345,
    name: "Farah Tim crew neck cotton sweatshirt in black",
    price: {
      current: {
        value: 95,
        text: "$95.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Black",
    colourWayId: 203502354,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121188700,
    productType: "Product",
    url: "farah/farah-tim-crew-neck-cotton-sweatshirt-in-black/prd/203502345?clr=black&colourWayId=203502354",
    imageUrl:
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-black/203502345-1-black",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-black/203502345-2",
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-black/203502345-3",
      "images.asos-media.com/products/farah-tim-crew-neck-cotton-sweatshirt-in-black/203502345-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969789,
    name: "Farah Hawtin loose fit pants in khaki",
    price: {
      current: {
        value: 129,
        text: "$129.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "GREEN",
    colourWayId: 202969798,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228373,
    productType: "Product",
    url: "farah/farah-hawtin-loose-fit-pants-in-khaki/prd/202969789?clr=green&colourWayId=202969798",
    imageUrl:
      "images.asos-media.com/products/farah-hawtin-loose-fit-pants-in-khaki/202969789-1-green",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-hawtin-loose-fit-pants-in-khaki/202969789-2",
      "images.asos-media.com/products/farah-hawtin-loose-fit-pants-in-khaki/202969789-3",
      "images.asos-media.com/products/farah-hawtin-loose-fit-pants-in-khaki/202969789-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969806,
    name: "Farah Parker ying yang printed short sleeve camp collar shirt in brown",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "BROWN",
    colourWayId: 202969815,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228368,
    productType: "Product",
    url: "farah/farah-parker-ying-yang-printed-short-sleeve-camp-collar-shirt-in-brown/prd/202969806?clr=brown&colourWayId=202969815",
    imageUrl:
      "images.asos-media.com/products/farah-parker-ying-yang-printed-short-sleeve-camp-collar-shirt-in-brown/202969806-1-brown",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-parker-ying-yang-printed-short-sleeve-camp-collar-shirt-in-brown/202969806-2",
      "images.asos-media.com/products/farah-parker-ying-yang-printed-short-sleeve-camp-collar-shirt-in-brown/202969806-3",
      "images.asos-media.com/products/farah-parker-ying-yang-printed-short-sleeve-camp-collar-shirt-in-brown/202969806-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969902,
    name: "Farah Brewer cotton long sleeve shirt in green",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "GREEN",
    colourWayId: 202969907,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228387,
    productType: "Product",
    url: "farah/farah-brewer-cotton-long-sleeve-shirt-in-green/prd/202969902?clr=green&colourWayId=202969907",
    imageUrl:
      "images.asos-media.com/products/farah-brewer-cotton-long-sleeve-shirt-in-green/202969902-1-green",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-brewer-cotton-long-sleeve-shirt-in-green/202969902-2",
      "images.asos-media.com/products/farah-brewer-cotton-long-sleeve-shirt-in-green/202969902-3",
      "images.asos-media.com/products/farah-brewer-cotton-long-sleeve-shirt-in-green/202969902-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969976,
    name: "Farah redwald linen shorts in white",
    price: {
      current: {
        value: 42.56,
        text: "$42.56",
      },
      previous: {
        value: 112,
        text: "$112.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "WHITE",
    colourWayId: 202970010,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228371,
    productType: "Product",
    url: "farah/farah-redwald-linen-shorts-in-white/prd/202969976?clr=white&colourWayId=202970010",
    imageUrl:
      "images.asos-media.com/products/farah-redwald-linen-shorts-in-white/202969976-1-white",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-redwald-linen-shorts-in-white/202969976-2",
      "images.asos-media.com/products/farah-redwald-linen-shorts-in-white/202969976-3",
      "images.asos-media.com/products/farah-redwald-linen-shorts-in-white/202969976-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202970171,
    name: "Farah Elm chino pants in navy",
    price: {
      current: {
        value: 103,
        text: "$103.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "NAVY",
    colourWayId: 202970173,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228425,
    productType: "Product",
    url: "farah/farah-elm-chino-pants-in-navy/prd/202970171?clr=navy&colourWayId=202970173",
    imageUrl:
      "images.asos-media.com/products/farah-elm-chino-pants-in-navy/202970171-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-elm-chino-pants-in-navy/202970171-2",
      "images.asos-media.com/products/farah-elm-chino-pants-in-navy/202970171-3",
      "images.asos-media.com/products/farah-elm-chino-pants-in-navy/202970171-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203502295,
    name: "Farah Haslam cotton polo in black",
    price: {
      current: {
        value: 71.5,
        text: "$71.50",
      },
      previous: {
        value: 95,
        text: "$95.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Black",
    colourWayId: 203502305,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121188704,
    productType: "Product",
    url: "farah/farah-haslam-cotton-polo-in-black/prd/203502295?clr=black&colourWayId=203502305",
    imageUrl:
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-black/203502295-1-black",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-black/203502295-2",
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-black/203502295-3",
      "images.asos-media.com/products/farah-haslam-cotton-polo-in-black/203502295-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203511152,
    name: "Farah Brewer cotton slim fit shirt in beige",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Beige",
    colourWayId: 203511172,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121211030,
    productType: "Product",
    url: "farah/farah-brewer-cotton-slim-fit-shirt-in-beige/prd/203511152?clr=beige&colourWayId=203511172",
    imageUrl:
      "images.asos-media.com/products/farah-brewer-cotton-slim-fit-shirt-in-beige/203511152-1-beige",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-brewer-cotton-slim-fit-shirt-in-beige/203511152-2",
      "images.asos-media.com/products/farah-brewer-cotton-slim-fit-shirt-in-beige/203511152-3",
      "images.asos-media.com/products/farah-brewer-cotton-slim-fit-shirt-in-beige/203511152-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 203502434,
    name: "Farah Elm stretch slim jeans in mid wash",
    price: {
      current: {
        value: 112,
        text: "$112.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "Blue",
    colourWayId: 203502439,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 121188681,
    productType: "Product",
    url: "farah/farah-elm-stretch-slim-jeans-in-mid-wash/prd/203502434?clr=blue&colourWayId=203502439",
    imageUrl:
      "images.asos-media.com/products/farah-elm-stretch-slim-jeans-in-mid-wash/203502434-1-blue",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-elm-stretch-slim-jeans-in-mid-wash/203502434-2",
      "images.asos-media.com/products/farah-elm-stretch-slim-jeans-in-mid-wash/203502434-3",
      "images.asos-media.com/products/farah-elm-stretch-slim-jeans-in-mid-wash/203502434-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202970011,
    name: "Farah Murphy tie dye shorts in blue",
    price: {
      current: {
        value: 52,
        text: "$52.00",
      },
      previous: {
        value: 69,
        text: "$69.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "BLUE",
    colourWayId: 202970029,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228420,
    productType: "Product",
    url: "farah/farah-murphy-tie-dye-shorts-in-blue/prd/202970011?clr=blue&colourWayId=202970029",
    imageUrl:
      "images.asos-media.com/products/farah-murphy-tie-dye-shorts-in-blue/202970011-1-blue",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-murphy-tie-dye-shorts-in-blue/202970011-2",
      "images.asos-media.com/products/farah-murphy-tie-dye-shorts-in-blue/202970011-3",
      "images.asos-media.com/products/farah-murphy-tie-dye-shorts-in-blue/202970011-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 201759610,
    name: "Farah swim trunks in orange",
    price: {
      current: {
        value: 17,
        text: "$17.00",
      },
      previous: {
        value: 42,
        text: "$42.00",
      },
      rrp: {
        value: 58,
        text: "$58.00",
      },
      isMarkedDown: true,
      isOutletPrice: true,
      currency: "USD",
    },
    colour: "Orange",
    colourWayId: 201759619,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 114878705,
    productType: "Product",
    url: "farah/farah-swim-trunks-in-orange/prd/201759610?clr=orange&colourWayId=201759619",
    imageUrl:
      "images.asos-media.com/products/farah-swim-trunks-in-orange/201759610-1-orange",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-swim-trunks-in-orange/201759610-2",
      "images.asos-media.com/products/farah-swim-trunks-in-orange/201759610-3",
      "images.asos-media.com/products/farah-swim-trunks-in-orange/201759610-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 201759633,
    name: "Farah hawaiian print swim trunks in blue",
    price: {
      current: {
        value: 19,
        text: "$19.00",
      },
      previous: {
        value: 42,
        text: "$42.00",
      },
      rrp: {
        value: 58,
        text: "$58.00",
      },
      isMarkedDown: true,
      isOutletPrice: true,
      currency: "USD",
    },
    colour: "Blue",
    colourWayId: 201759635,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 114878710,
    productType: "Product",
    url: "farah/farah-hawaiian-print-swim-trunks-in-blue/prd/201759633?clr=blue&colourWayId=201759635",
    imageUrl:
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-blue/201759633-1-blue",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-blue/201759633-2",
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-blue/201759633-3",
      "images.asos-media.com/products/farah-hawaiian-print-swim-trunks-in-blue/201759633-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 201759650,
    name: "Farah swim trunks in navy",
    price: {
      current: {
        value: 25.5,
        text: "$25.50",
      },
      previous: {
        value: 42,
        text: "$42.00",
      },
      rrp: {
        value: 58,
        text: "$58.00",
      },
      isMarkedDown: true,
      isOutletPrice: true,
      currency: "USD",
    },
    colour: "Navy",
    colourWayId: 201759656,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 114878703,
    productType: "Product",
    url: "farah/farah-swim-trunks-in-navy/prd/201759650?clr=navy&colourWayId=201759656",
    imageUrl:
      "images.asos-media.com/products/farah-swim-trunks-in-navy/201759650-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-swim-trunks-in-navy/201759650-2",
      "images.asos-media.com/products/farah-swim-trunks-in-navy/201759650-3",
      "images.asos-media.com/products/farah-swim-trunks-in-navy/201759650-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969764,
    name: "Farah Colbert swim shorts in pink",
    price: {
      current: {
        value: 25,
        text: "$25.00",
      },
      previous: {
        value: 60,
        text: "$60.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "PINK",
    colourWayId: 202969774,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228404,
    productType: "Product",
    url: "farah/farah-colbert-swim-shorts-in-pink/prd/202969764?clr=pink&colourWayId=202969774",
    imageUrl:
      "images.asos-media.com/products/farah-colbert-swim-shorts-in-pink/202969764-1-pink",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-colbert-swim-shorts-in-pink/202969764-2",
      "images.asos-media.com/products/farah-colbert-swim-shorts-in-pink/202969764-3",
      "images.asos-media.com/products/farah-colbert-swim-shorts-in-pink/202969764-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202970124,
    name: "Farah Murphy cut and sew shorts in navy",
    price: {
      current: {
        value: 52,
        text: "$52.00",
      },
      previous: {
        value: 69,
        text: "$69.00",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: true,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "NAVY",
    colourWayId: 202970148,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228412,
    productType: "Product",
    url: "farah/farah-murphy-cut-and-sew-shorts-in-navy/prd/202970124?clr=navy&colourWayId=202970148",
    imageUrl:
      "images.asos-media.com/products/farah-murphy-cut-and-sew-shorts-in-navy/202970124-1-navy",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-murphy-cut-and-sew-shorts-in-navy/202970124-2",
      "images.asos-media.com/products/farah-murphy-cut-and-sew-shorts-in-navy/202970124-3",
      "images.asos-media.com/products/farah-murphy-cut-and-sew-shorts-in-navy/202970124-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969665,
    name: "Farah Trehurst check shorts in yellow",
    price: {
      current: {
        value: 103,
        text: "$103.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "YELLOW",
    colourWayId: 202969667,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228398,
    productType: "Product",
    url: "farah/farah-trehurst-check-shorts-in-yellow/prd/202969665?clr=yellow&colourWayId=202969667",
    imageUrl:
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-yellow/202969665-1-yellow",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-yellow/202969665-2",
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-yellow/202969665-3",
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-yellow/202969665-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 202969924,
    name: "Farah Trehurst check shorts in lilac",
    price: {
      current: {
        value: 103,
        text: "$103.00",
      },
      previous: {
        value: null,
        text: "",
      },
      rrp: {
        value: null,
        text: "",
      },
      isMarkedDown: false,
      isOutletPrice: false,
      currency: "USD",
    },
    colour: "LILAC",
    colourWayId: 202969942,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 119228411,
    productType: "Product",
    url: "farah/farah-trehurst-check-shorts-in-lilac/prd/202969924?clr=lilac&colourWayId=202969942",
    imageUrl:
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-lilac/202969924-1-lilac",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-lilac/202969924-2",
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-lilac/202969924-3",
      "images.asos-media.com/products/farah-trehurst-check-shorts-in-lilac/202969924-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: false,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
  {
    id: 201759611,
    name: "Farah swim trunks in purple",
    price: {
      current: {
        value: 12,
        text: "$12.00",
      },
      previous: {
        value: 42,
        text: "$42.00",
      },
      rrp: {
        value: 58,
        text: "$58.00",
      },
      isMarkedDown: true,
      isOutletPrice: true,
      currency: "USD",
    },
    colour: "Purple",
    colourWayId: 201759620,
    brandName: "Farah",
    hasVariantColours: false,
    hasMultiplePrices: false,
    groupId: null,
    productCode: 114878709,
    productType: "Product",
    url: "farah/farah-swim-trunks-in-purple/prd/201759611?clr=purple&colourWayId=201759620",
    imageUrl:
      "images.asos-media.com/products/farah-swim-trunks-in-purple/201759611-1-purple",
    additionalImageUrls: [
      "images.asos-media.com/products/farah-swim-trunks-in-purple/201759611-2",
      "images.asos-media.com/products/farah-swim-trunks-in-purple/201759611-3",
      "images.asos-media.com/products/farah-swim-trunks-in-purple/201759611-4",
    ],
    videoUrl: null,
    showVideo: false,
    isSellingFast: true,
    sponsoredCampaignId: null,
    facetGroupings: [],
    advertisement: null,
  },
];
